запусти браузер:
- browser запускаю браузер
запусти сервак:
- ssh_connect введи домен и мы на месте
интернет открой:
- browser открываю браузер
открой браузер:
- browser интернет активирован
сервер:
- ssh2_connect коннекчусь к железке
покажи список:
- show_list_device вот список устройств
настроить:
- telnet_connect коннекчусь к железу
посмотреть фильм:
- browser сейчас открою браузер
работаешь:
- passive не найден

